//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.18 at 07:30:24 PM CEST 
//


package nl.tue.hti.g33.thermostat.parser;

import javax.xml.namespace.QName;

import ae.javax.xml.bind.JAXBElement;
import ae.javax.xml.bind.annotation.XmlElementDecl;
import ae.javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Thermostat_QNAME = new QName("", "thermostat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link ThermostatType }
     * 
     */
    public ThermostatType createThermostatType() {
        return new ThermostatType();
    }

    /**
     * Create an instance of {@link WeekProgram }
     * 
     */
    public WeekProgram createWeekProgram() {
        return new WeekProgram();
    }

    /**
     * Create an instance of {@link Day.Switch }
     * 
     */
    public Day.Switch createDaySwitch() {
        return new Day.Switch();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThermostatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thermostat")
    public JAXBElement<ThermostatType> createThermostat(ThermostatType value) {
        return new JAXBElement<ThermostatType>(_Thermostat_QNAME, ThermostatType.class, null, value);
    }

}
