//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.18 at 07:30:24 PM CEST 
//


package nl.tue.hti.g33.thermostat.parser;

import java.math.BigDecimal;
import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThermostatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThermostatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="current_day" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="current_temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="target_temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="day_temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="night_temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="week_program_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="week_program" type="{}WeekProgram"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThermostatType", propOrder = {
    "currentDay",
    "time",
    "currentTemperature",
    "targetTemperature",
    "dayTemperature",
    "nightTemperature",
    "weekProgramState",
    "weekProgram"
})
public class ThermostatType {

    @XmlElement(name = "current_day", required = true)
    protected String currentDay;
    @XmlElement(required = true)
    protected String time;
    @XmlElement(name = "current_temperature", required = true)
    protected BigDecimal currentTemperature;
    @XmlElement(name = "target_temperature", required = true)
    protected BigDecimal targetTemperature;
    @XmlElement(name = "day_temperature", required = true)
    protected BigDecimal dayTemperature;
    @XmlElement(name = "night_temperature", required = true)
    protected BigDecimal nightTemperature;
    @XmlElement(name = "week_program_state", required = true)
    protected String weekProgramState;
    @XmlElement(name = "week_program", required = true)
    protected WeekProgram weekProgram;

    /**
     * Gets the value of the currentDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentDay() {
        return currentDay;
    }

    /**
     * Sets the value of the currentDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentDay(String value) {
        this.currentDay = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the currentTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentTemperature() {
        return currentTemperature;
    }

    /**
     * Sets the value of the currentTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentTemperature(BigDecimal value) {
        this.currentTemperature = value;
    }

    /**
     * Gets the value of the targetTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTargetTemperature() {
        return targetTemperature;
    }

    /**
     * Sets the value of the targetTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTargetTemperature(BigDecimal value) {
        this.targetTemperature = value;
    }

    /**
     * Gets the value of the dayTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDayTemperature() {
        return dayTemperature;
    }

    /**
     * Sets the value of the dayTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDayTemperature(BigDecimal value) {
        this.dayTemperature = value;
    }

    /**
     * Gets the value of the nightTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNightTemperature() {
        return nightTemperature;
    }

    /**
     * Sets the value of the nightTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNightTemperature(BigDecimal value) {
        this.nightTemperature = value;
    }

    /**
     * Gets the value of the weekProgramState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekProgramState() {
        return weekProgramState;
    }

    /**
     * Sets the value of the weekProgramState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekProgramState(String value) {
        this.weekProgramState = value;
    }

    /**
     * Gets the value of the weekProgram property.
     * 
     * @return
     *     possible object is
     *     {@link WeekProgram }
     *     
     */
    public WeekProgram getWeekProgram() {
        return weekProgram;
    }

    /**
     * Sets the value of the weekProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeekProgram }
     *     
     */
    public void setWeekProgram(WeekProgram value) {
        this.weekProgram = value;
    }

}
